### ISSUE TITLE
Cordova: Not able to find the threats in the release sign build

### ISSUE THREAD

**Issue by nyayadhish20** [talsec/Free-RASP-Cordova#26]
I am using telsec freeRASP Cordova plugin lib: 5.4.0.

The issue I am facing is that in the development environment, I can get the callback for the Threats that Telsec finds.
But when I make a signed APK it does not give any callback for success or failure.

Cordova-android version: 12.0.1

Feel free to let me know if you need more information from me.

Thanks,

**Comment by tompsota** [comment]
Hi @nyayadhish20,

Can you write down which callbacks are you expecting to receive in production build? 

When going from dev to prod build, it is expected that some callbacks won't get triggered on secure devices (for example debug callback will usually be triggered in dev build, but not in prod build)

Best,
Tomas from Talsec

**Comment by nyayadhish20** [comment]
@tompsota 
Thanks for your reply.

I am looking for the callbacks for debug, privilegedAccess, appIntegrity, and hooks.

I understand that on secure devices privilegedAccess, appIntegrity and hooks will not get triggered, but debug should get triggered if USB debugging is turned on and the device is connected to adb in prod build.

I have also tested on an unsecured device, and none of the callbacks are getting triggered on the prod build.

Regards, 
Nikhil

**Comment by msikyna** [comment]
Hello @nyayadhish20 ,

could you also try that with the example application included in the repository?

Kind regards,
Talsec team

**Comment by Adityakhandelwal021** [comment]
Hello 
i successfully install the plugin after and add  config and action sucessfully 
but when i create signed debug apk and install it into my phone and inspect the application using usb and chrome dev tool i get an error : - ReferenceError: TalsecPlugin is not defined
so please tell me how can i import plugin in my component

**Comment by tompsota** [comment]
Hello @nyayadhish20,

If you are using Angular in your app, can you try the fix proposed in #27?

In case there won't be any further activity, I'll close the issue.

Cheers,
Tomas from Talsec
