### ISSUE TITLE
Ionic cordova angular import issue 

### ISSUE THREAD

**Issue by Adityakhandelwal021** [talsec/Free-RASP-Cordova#27]
Hello
i successfully install the plugin after and add config and action sucessfully
but when i create signed debug apk and install it into my phone and inspect the application using usb and chrome dev tool i get an error : - ReferenceError: TalsecPlugin is not defined
so please tell me how can i import plugin in my component

**Comment by tompsota** [comment]
Hi @Adityakhandelwal021,

The signed debug apk of our demo app works as expected, so the problem may be on the angular side.

To assist you better with the issue you're encountering, could you please provide a minimal reproducible example? This will help us understand the problem more clearly. 

Thanks,
Tomas from Talsec

**Comment by codehack26** [comment]
@Adityakhandelwal021 
After installing the plugin add the below code at the end of imports

declare var talsec: any;

@tompsota You can close this issue.
