### ISSUE TITLE
Get unofficialStore threat while installing app from Visual Studio App Center

### ISSUE THREAD

**Issue by privaterepo2021** [talsec/Free-RASP-Cordova#3]
Is there a way to add Visual Studio App Center to the supportedAlternativeStores array list?

**Comment by msikyna** [comment]
Hello @privaterepo2021 ,

the supportedAlternativeStores accepts a package name of the application, which installs your app. If you are downloading the APK from App Center, it might be installed by Android package installer. Try to include the **com.google.android.packageinstaller** or **com.android.packageinstaller**. However, this will allow installing your APK directly even not from App Center, therefore do not use it later in production.
Let us know, if it helped.

Kind regards,
Matúš, Talsec developer

**Comment by privaterepo2021** [comment]
Hi @msikyna, thank you for the quick response. I had tried out the solution and it works.

**Comment by privaterepo2021** [comment]
Hi @msikyna, I just checked that actually the plugin did not show unofficial store threat because the plugin has fail to init.

This is my configuration:

"tlacConfig": {
        "androidConfig" : {
            "packageName" : "com.ebworx.bdimicroapps", 
            "certificateHash" : "2ZYTi+Z2PGVzO1QZcVcMZ1GTmpebaNKFFoE+LVJd0AI=",
            "supportedAlternativeStores": [
                "com.google.android.packageinstaller",
                "com.android.packageinstaller"
            ]
        },
        "iosConfig" : {
            "appBundleIds": "com.ebworx.bdimicroapps",
            "appTeamId": "BLM26UAEJ2"
        },
        "watcherMail" : null
    }

This is from the debugger:
D/PluginManager: getPlugin - put: TalsecPlugin
W/CordovaPlugin: Attempted to send a second callback for ID: TalsecPlugin451479080
    Result was: "Invalid action"

**Comment by privaterepo2021** [comment]
Hi @msikyna, I just checked that actually the plugin did not show unofficial store threat because the plugin has fail to init.

This is my configuration:


> "tlacConfig": {
>         "androidConfig" : {
>             "packageName" : "com.eb.sps", 
>             "certificateHash" : "2ZYTL+Z2gGVzO1QZ2VcMZ1GT1pebaNKFFoE+LVJd0AI=",
>             "supportedAlternativeStores": [
>                 "com.google.android.packageinstaller",
>                 "com.android.packageinstaller"
>             ]
>         },
>         "iosConfig" : {
>             "appBundleIds": "com.eb.sps",
>             "appTeamId": "BLT26AAEG2"
>         },
>         "watcherMail" : null
>     }

This is from the debugger:

> D/PluginManager: getPlugin - put: TalsecPlugin
> W/CordovaPlugin: Attempted to send a second callback for ID: TalsecPlugin451479080
>     Result was: "Invalid action"

**Comment by tompsota** [comment]
Hello @privaterepo2021,

this is happening because your config is nested under `tlacConfig` key and therefore freeRASP is not able to parse it correctly.
A valid config would look like this:
```
    var config = {
        androidConfig : {
            packageName : "com.eb.sps",
            certificateHash : "2ZYTL+Z2gGVzO1QZ2VcMZ1GT1pebaNKFFoE+LVJd0AI=",
            supportedAlternativeStores : [
                "com.google.android.packageinstaller",
                "com.android.packageinstaller"
            ]
        },
        iosConfig : {
            appBundleIds : "com.eb.sps",
            appTeamId : "BLT26AAEG2"
        },
        watcherMail : null 
    };
```

Try to pass object with this structure into `talsec.start` and let us know if that helped.

_(Also don't forget to update the `watcherMail` ;) )_

Best,
Tomas, Talsec developer

**Comment by privaterepo2021** [comment]
Hi @tompsota, I had check the plugin code, looks like supportedAlternativeStores is not supported for the current master branch of this plugin? 

 ```
private fun parseTalsecConfigThrowing(configJson: String): TalsecConfig {
        val json = JSONObject(configJson)
        val androidConfig = json.getJSONObject("androidConfig")
        val packageName = androidConfig.getString("packageName")
        val certificateHash = androidConfig.getString("certificateHash")
        val watcherMail = json.getString("watcherMail")
        val alternativeStores = mutableListOf<String>()
        if (androidConfig.has("supportedAlternativeStores")) {
            val stores = androidConfig.getJSONArray("supportedAlternativeStores")
            for (i in 0 .. stores.length()) {
                alternativeStores.add(stores.getString(i))
            }
        }
        return TalsecConfig(packageName, certificateHash, watcherMail, null)
}
```

this is my function 

```
initTLAC(){
        var config = {
            "androidConfig" : {
                "packageName" : "com.eb.sps", 
                "certificateHash" : "2ZYTL+Z2gGVzO1QZ2VcMZ1GT1pebaNKFFoE+LVJd0AI=",
                "supportedAlternativeStores": [
                    "com.google.android.packageinstaller",
                    "com.android.packageinstaller"
                ]
            },
            "iosConfig" : {
                "appBundleIds": "com.eb.sps",
                "appTeamId": "BLT26AAEG2"
            },
            "watcherMail" : "tmlee@gmail.com"
        }; //serverConfig["tlacConfig"];
        var threatListener = (threatType)=>{
            this.logService.log("threat", threatType);
            switch(threatType) {
                case "privilegedAccess": // Android & iOS
                    let isEnableEmulator = serverConfig["isEnableEmulator"];
                    if(window.device.isVirtual) {
                        if(!isEnableEmulator) {
                            this.showRootEmulatorErrorMessage();
                        }
                    }
                    break;
                case "debug": // Android & iOS
                case "simulator": // Android & iOS
                case "appIntegrity": // Android & iOS
                case "unofficialStore": // Android & iOS
                case "hooks": // Android & iOS
                case "device binding": // Android & iOS
                case "deviceID": // iOS only
                case "missingSecureEnclave": // iOS only
                case "passcodeChange": // iOS only
                case "passcode": // iOS only
                    this.showRootEmulatorErrorMessage();
                    break;
                default:
                    console.log('Unknown threat type detected: ' + threatType);
                    this.showRootEmulatorErrorMessage();
            }
        };

        window.talsec.start(config, threatListener).then(() => {
            this.logService.log('Talsec initialized.');
        }).catch((error) => {
            this.logService.log('Error during Talsec initialization: ', error);
            // this.showRootEmulatorErrorMessage();
        });
}
```
I had try with your suggestion but still hit the same error.
If I removed the  supportedAlternativeStores array list then it can work.

**Comment by msikyna** [comment]
Hi @privaterepo2021 ,

you are right, there was a slight bug in the master branch regarding the supportedAlternativeStores.. it will be fixed in a moment, as today, we are releasing a v2.0.0.

There will be one more API change, certificateHash is now certificateHashes : ["your_signing_certificate_hash_base64"]; see the array, it now supports more certificate hashes.

**Comment by privaterepo2021** [comment]
Hi @msikyna, I will test it out with the new version of the plugin. Thanks, have a great day 👍

**Comment by privaterepo2021** [comment]
Hi @msikyna @tompsota , I still got the error after upgrading to the latest 2.0.0 version. Is there anything I miss out?

```
W/CordovaPlugin: Attempted to send a second callback for ID: TalsecPlugin1771000586
    Result was: "Invalid action"
D/PluginManager: exec() call to unknown plugin: DeleteLaunchScreenCache
I/chromium: [INFO:CONSOLE(1)] "Error during Talsec initialization: ", source: file:///android_asset/www/static/js/main.840d2e30.js (1)
```

This is my function

```
initTLAC(){
        var config = {
            "androidConfig" : {
                "packageName" : "com.eb.sps", 
                "certificateHash" : ["2ZYTi+Z2PGVzO1QZcVcMZ1GTmpebaNKFFoE+LVJd0AI="],
                "supportedAlternativeStores": [
                    "com.google.android.packageinstaller",
                    "com.android.packageinstaller"
                ]
            },
            "iosConfig" : {
                "appBundleIds": "com.eb.sps",
                "appTeamId": "BLT26AAEG2"
            },
            "watcherMail" : "tmlee@gmail.com"
        }; //serverConfig["tlacConfig"];
        var threatListener = (threatType)=>{
            this.logService.log("threat", threatType);
            switch(threatType) {
                case "privilegedAccess": // Android & iOS
                    let isEnableEmulator = serverConfig["isEnableEmulator"];
                    if(window.device.isVirtual) {
                        if(!isEnableEmulator) {
                            this.showRootEmulatorErrorMessage();
                        }
                    }
                    break;
                case "debug": // Android & iOS
                case "simulator": // Android & iOS
                case "appIntegrity": // Android & iOS
                case "unofficialStore": // Android & iOS
                case "hooks": // Android & iOS
                case "device binding": // Android & iOS
                case "deviceID": // iOS only
                case "missingSecureEnclave": // iOS only
                case "passcodeChange": // iOS only
                case "passcode": // iOS only
                    this.showRootEmulatorErrorMessage();
                    break;
                default:
                    console.log('Unknown threat type detected: ' + threatType);
                    this.showRootEmulatorErrorMessage();
            }
        };

        window.talsec.start(config, threatListener).then(() => {
            this.logService.log('Talsec initialized.');
        }).catch((error) => {
            this.logService.log('Error during Talsec initialization: ', error);
            // this.showRootEmulatorErrorMessage();
        });
}
```

**Comment by privaterepo2021** [comment]
I using

"@angular/core": "11.0.2"
"cordova-android": "11.0.0"
"cordova-ios": "6.2.0"

**Comment by tompsota** [comment]
@privaterepo2021 There was a breaking change in the API in v2.0.0, please change `certificateHash` to `certificateHashes`. in your config.

**Comment by privaterepo2021** [comment]
Hi @tompsota  thanks for pointing out the mistake, it works now 👍

**Comment by privaterepo2021** [comment]
Hi @tompsota , are we able to add supportedAlternativeStores for ios config? Seems like IOS is also hitting unofficial store threat if I build Ipa from xcode

**Comment by msikyna** [comment]
Hello @privaterepo2021 ,
the iOS only supports an official way (AppStore or TestFlight) of installing the application. Building an IPA from Xcode correctly hits the unofficial store threat.

Kind regards,
Matúš, Talsec developer
