### ISSUE TITLE
Root Detection not working in Android

### ISSUE THREAD

**Issue by codehack26** [talsec/Free-RASP-Cordova#30]
**Describe the bug**
Able to launch the app on a rooted device with Talsec

**To Reproduce**
If applicable, steps to reproduce the behavior.
1. Install the app 
2. Clear cache & clear data
3. You will be able to use the app on the rooted device 

**Expected behavior**
It should detect root detection everytime on app start

**Screenshots**

**Please complete the following information:**
 - Device: Moto , Real 3 pro
 - OS version: 11, 10
 - Version of freeRASP: 6.1.1

**Additional context**

**Comment by tompsota** [comment]
Hi @codehack26,

Please answer following questions:

- Are you referring to a physical device or emulators?
- Are you using the prod version (i.e. `isProd: true` in config)?

Thanks,
Tomas from Talsec

**Comment by tompsota** [comment]
The plugin evaluates root detection periodically, did you try to wait a couple of minutes to see if you get another callback? Waiting up to 5 min. should be enough. As long as freeRASP is still running, you should receive the callback.

**Comment by codehack26** [comment]
@tompsota Waiting for minutes or upto 5min will not be helpful. Hacker can perform malicious activity within the particular timeframe.

**Comment by tompsota** [comment]
@codehack26, I understand.

The problem lies in fact that once the SDK detects a threat, it sends it as a one-time event to javascript and currently there is no mechanism that would allow you to request the callback again. 

Can you explain exactly how you clean the data and cache?

Thanks,
Tomas from Talsec
