### ISSUE TITLE
Talsec Kotlin version is conflict with Firebase reCAPTCHA Kotlin version

### ISSUE THREAD

**Issue by Meng991003** [talsec/Free-RASP-Cordova#35]
**Describe the bug**
The kotlin version for Talsec is 1.7.10 where the kotlin version required for Firebase reCAPTCHA is 1.9.0. When i trying to build my project in Android Studio, i getting error if I set the kotlin version to 1.7.10 but it working fine if i set it to 1.9.0. Wanted to check if there is any concern if i set the Kotlin version to 1.9.0 for talsec as well? 
**

**

**Comment by tompsota** [comment]
Hi @Meng991003,

freeRASP should work with higher Kotlin versions just fine.

Let us know whether you were able to run your app successfully.

Best,
Tomas from Talsec


Best,
Tomas from Talsec
