### ISSUE TITLE
Artifact/dependency from docs is 404

### ISSUE THREAD

**Issue by mchl18** [talsec/Free-RASP-Cordova#40]
**Describe the bug**
I was checking out your docs at https://docs.talsec.app/freerasp/integration/cordova#install-the-plugin and came across this instruction:

```
Set Talsec's Artifact Registry in your project's build.gradle (or settings.gradle if you are using settings repositories):

[build.gradle (:project)]
Copy
repositories {
    google()
    mavenCentral()
    maven { url "https://jitpack.io" }
    maven { url "https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp" }
}
```

Howeve it appears that this link is dead, it leads to a 404 page:
https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp

**To Reproduce**
If applicable, steps to reproduce the behavior.

**Expected behavior**
Either update or remove the link

**Screenshots**

**Please complete the following information:**
 - OS version: [e.g. iOS8.1]
 - Version of freeRASP: [e.g. 22]

**Additional context**

**Comment by msikyna** [comment]
Hello @mchl18,
A dependency is hosted on the link, see further:
`dependencies {
    // freeRASP SDK  
    implementation 'com.aheaditec.talsec.security:TalsecSecurity-Community:9.1.0'
}`

Could you try if you can download it successfully?

Kind regards,
Talsec team
