### ISSUE TITLE
Support for Capacitor

### ISSUE THREAD

**Issue by rgbaman** [talsec/Free-RASP-Cordova#5]
**Is your feature request related to a problem? Please describe.**
No (apart from you don't support Capacitor).

**Describe the solution you'd like**
I've been searching for a stable RASP library for a long time and saw yours and thought about purchasing the commercial licence. I'd very much like to see a version for Capacitor though (https://www.capacitorjs.com).

The Capacitor community is growing massively and believe this would be an incredibly popular security addition.

I'd also like to see it packaged on node and installed using npm.

**Describe alternatives you've considered**
Running it through Cordova but we don't use Cordova due to conflicting libraries in parts of our app.

**Comment by syakymchuk** [comment]
Hello @rgbaman, 

We can discuss adding Capacitor.  Would you mind slotting a quick call session [here in Calendly ](https://calendly.com/sergiy-yakymchuk-1/60min?month=2023-02 )?  

Thanks you.

**Comment by tompsota** [comment]
Hi @rgbaman,

It's exciting to announce that freeRASP is now compatible with Capacitor! If you wish to learn more, check out our new plugin here: https://github.com/talsec/Free-RASP-Capacitor. 

Cheers,

Tomas from Talsec
